### ISSUE TITLE
Send Real IP User to APM Server

### ISSUE THREAD

**Issue by fontebasso** [ssi-anik/elastic-apm-php#2]
Houston, I have a problem!

After many hours believing that my stack had some configuration error, I can't imagine who is not getting the user real IP, my last analysis indicates that the agent or package it is not looking for the correct IP.

My stack is all Kubernetes with 2 clusters on AWS:

[My User] ---https://my-app.com---> [K8s 1 - Run APM PHP Agent] ---https://apm-server.com:8200---> [K8s 2 - Run APM] ---http://es.cluster.local:9200---> [K8s 2 - Run Elasticsearch]

This package has the possibility to define the user IP (field `client.ip`) in APM?

**Comment by ssi-anik** [comment]
what apm version you're using? I'll check by myself. using with Laravel?

**Comment by fontebasso** [comment]
- APM Server: 7.9.3
- APM Agent PHP: 0.3
- Laravel: 8

**Comment by ssi-anik** [comment]
I have checked locally, I found `host.ip` in the transaction object. I guess it's been captured by the APM server. And, the package doesn't capture the user's IP. but if you need to pass the user's IP then attach it in a span and set the user's IP. You'll get that in the elastic's object.
