### ISSUE TITLE
"Class 'Elastic\\Apm\\ElasticApm' not found"

### ISSUE THREAD

**Issue by nerijuso** [ssi-anik/elastic-apm-php#6]
Hi,
I installed your library and tried to use, but I am getting error that "Class 'Elastic\\Apm\\ElasticApm' not found". I installed apm server and when I do request to server http://localhost:8200/ it responds me with 200 code. 
my elastic_apm.ini config 
`extension=elastic_apm.so
elastic_apm.enabled=true
elastic_apm.bootstrap_php_part_file=/var/apm-agent/apm/src/bootstrap_php_part.php
elastic_apm.server_url="host.docker.internal:8200"
elastic_apm.service_name="PHP APM Test Service"
elastic_apm.log_level=DEBUG
`
Any idea why this class can't be found? Thanks

**Comment by ssi-anik** [comment]
I guess due to it's breaking changes. The dependency itself is not stable.
