### ISSUE TITLE
lumen

### ISSUE THREAD

**Issue by mnbp1371** [ssi-anik/elastic-apm-php#7]
I installed this package by composer but the below error occurred:

`Class apm-agent does not exist.`

Is there any requirements for this package? Or what should I do for config that?

**Comment by ssi-anik** [comment]
Firstly, did you register the provider? do you have the agent extension installed on your host machine? 
Secondly, due to the breaking changes in the elastic apm agent, it'll break. it will not be maintained due to the breaking changes. after the agent become stable, will work on it hopefully.

**Comment by mnbp1371** [comment]
I had registered the provider in app.php  and i had installed the apm-agent-php from `https://github.com/elastic/apm-agent-php/releases/tag/v1.0.0`

Now I get the following error:
`Call to undefined method Elastic\Apm\Impl\Span::setLabel()`

This seems to be a problem with your package.
Do I guess right?


tanks

**Comment by ssi-anik** [comment]
Firstly, the package was unmaintained due to the instability of the dependency. and check the installation process. https://www.elastic.co/guide/en/apm/agent/php/current/setup.html

**Comment by mnbp1371** [comment]
seyed php agent extention works and sends all the reports to the apm system but your package gives the error I told you about.
It should be noted that I am using the lumen.

**Comment by ssi-anik** [comment]
If you missed the readme, please go through it again. Thanks.
![image](https://user-images.githubusercontent.com/2676602/112978619-64043600-9179-11eb-8154-565ea0d66687.png)
https://github.com/ssi-anik/elastic-apm-php/blob/03ddc1c2283474394a309dd42e0d5de7aa9cccf8/readme.md
