### ISSUE TITLE
Call to undefined function Anik\ElasticApm\Middleware\now()

### ISSUE THREAD

**Issue by biswajit-landmarkgroup** [ssi-anik/elastic-apm-php#9]
Uncaught exception 'Error' with message 'Call to undefined function Anik\ElasticApm\Middleware\now()' in /var/www/vendor/anik/elastic-apm-php/src/Middleware/RecordForegroundTransaction.php:87

Raised a PR for this.
Also the error transactions not showing in the Elastic APM.

FYI, Elastic APM is stable now for php

**Comment by ssi-anik** [comment]
Due to some personal urgencies, I can't actually work on this project and no time soon. If you want to help everyone will appreciate it.

**Comment by biswajit-landmarkgroup** [comment]
I have modified the changes in the PR. Could you please verify and merge the same. Thanks in advance.

**Comment by ssi-anik** [comment]
tagged `v2.1`
